#Choose which custom enchants to enable
#They will still remain on the items but wont do anything
#To disable the crafting recipes you have to reload the server
AntigravityEnabled: true
AutosmeltEnabled: true
BeheadingEnabled: true
DeflectEnabled: true
DirectEnabled: true
EyesofowlEnabled: true
ExperienceboostEnabled: true
FeedingmoduleEnabled: true
HealthboostEnabled: true
HeavenslightnessEnabled: true
IcyEnabled: true
LavawalkerEnabled: true
LeapingEnabled: true
LifestealEnabled: true
LumberjackEnabled: true
ReplantingEnabled: true
ShadowstepEnabled: true
StonefistsEnabled: true
ThermalplatingEnabled: true
TravelerEnabled: true
UnbreakableEnabled: true
VeinmineEnabled: true
WideEnabled: true

#Set the max level vanilla enchants can become using the plugin
MaxVanillaEnchantLevel: 10

#Choose whether you want to enable the smelting from
#rotten flesh to leather for easier creation of books
LeatherSmeltEnabled: true

#Percentage chance that the wandering trader spawns with a custom enchant offer
#Set to 0 for no special offers
WanderingTraderChance: 20

#Set the amount of emeralds the deflect enchant uses every time it deflects damage
DeflectCost: 1

VeinmineBlocks:
    - IRON_ORE
    - GOLD_ORE
    - COPPER_ORE
    - COAL_ORE
    - DIAMOND_ORE
    - EMERALD_ORE
    - LAPIS_ORE
    - REDSTONE_ORE
    
#Choose how to activate the veinmine enchant, choose between SNEAKING, STANDING or BOTH:
VeinmineMode: SNEAKING    
    
LumberjackBlocks:
    - ACACIA_LOG
    - OAK_LOG
    - SPRUCE_LOG
    - BIRCH_LOG
    - DARK_OAK_LOG
    - JUNGLE_LOG
    
#Choose how to activate the lumberjack enchant, choose between SNEAKING, STANDING or BOTH:
LumberjackMode: SNEAKING

#Choose whether to enable saturation mode on the feeding module
#which causes you to eat immediatly when loosing half a hunger bar 
#in order to keep your health full
EnableSaturationMode: false

#Which foods will be eaten by the feeding module enchant. HAS TO BE EDIBLE
FeedingModuleFoods:
    - APPLE
    - BAKED_POTATO
    - BEETROOT
    - BEETROOT_SOUP
    - BREAD
    - CARROT
    - COOKED_BEEF
    - COOKED_CHICKEN
    - COOKED_COD
    - COOKED_MUTTON
    - COOKED_PORKCHOP
    - COOKED_RABBIT
    - COOKED_SALMON
    - COOKIE
    - GLOW_BERRIES
    - GOLDEN_CARROT
    - HONEY_BOTTLE
    - MELON_SLICE
    - MUSHROOM_STEW
    - POTATO
    - PUMPKIN_PIE
    - RABBIT_STEW
    - SWEET_BERRIES
    
#Choose how to activate the wide enchant, for hoeing farmland,
#pathing dirt and stripping wood
#choose between SNEAKING, STANDING or BOTH:
WideSpecialActionMode: SNEAKING
    
    
    
    
    
